version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-web-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=【ここを外部DB用に書き換え】
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5000:80"
    # depends_on は不要になるので削除
    volumes:
      - ./WebApplication1/appsettings.json:/app/appsettings.json
      - ./dataprotection-keys:/root/.aspnet/DataProtection-Keys

    # postgres サービスをコメントアウトまたは削除
  # postgres:
  #   image: postgres:latest
  #   container_name: postgres-db
  #   environment:
  #     POSTGRES_PASSWORD: your_password
  #     POSTGRES_DB: your_database
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./postgres-data:/var/lib/postgresql/data
  #     - ./init.sql:/docker-entrypoint-initdb.d/init.sql
