version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-web-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=web_sql_smr1_user;Port=5432;Database=web_sql_smr1;User Id=web_sql_smr1_user;Password=6NFOQ5aK39jKpZCXUz6azqoqIKPXB9vR
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5000:80"
    depends_on:
      - postgres
    volumes:
      - ./WebApplication1/appsettings.json:/app/appsettings.json
      - ./dataprotection-keys:/root/.aspnet/DataProtection-Keys

      # ここでSSHキーをマウント
      #- ~/.ssh:/root/.ssh:ro

  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
